print("Należność za obiad w restauracji wynosi razem z napiwkiem 159 zł, a Ty")
print("postanawiasz ze swoimi przyjaciółmi podzielić ją na 4 równe części. Ile")
print("każde z Was będzie musiało zapłacić?")
input("Aby się dowiedzieć, naciśnij klawisz Enter.")
print("159 / 4 =", 159 / 4)
input("\n\nAby zakończyć program, naciśnij klawisz Enter.")
